---
- name: Configure FortiOS device
  gather_facts: false
  hosts: Fortigate
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 80
  tasks:
    - name: Configure global attributes.
      fortios_system_global:
        vdom: "{{ vdom }}"
        system_global:
          hostname: 'Fortigate0Tn'
