---
- name: "Show FortiGate firewall policies with status DISABLED only"
  hosts: Fortigate
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    vdom_name: "root"

  tasks:
    - name: Get firewall policies from configuration
      fortios_configuration_fact:
        vdom: "{{ vdom_name }}"
        selector: "firewall_policy"
      register: config_policies

    - name: Show only disabled policies
      debug:
        msg: "⚠️ Policy ID {{ policy.policyid }} - '{{ policy.name | default('No Name') }}' is DISABLED"
      loop: "{{ config_policies.meta.results }}"
      loop_control:
        loop_var: policy
        label: "{{ policy.name | default('No Name') }}"
      when:
        - policy.status is defined
        - policy.status == "disable"

