---
- name: Configure DNS on FortiGate
  hosts: Fortigate
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"
    primary_dns: "8.8.8.8"
    secondary_dns: "8.8.4.4"

  tasks:
    - name: Gather current DNS configuration
      fortios_facts:
        vdom: "{{ vdom }}"
        selector: "system_dns"
      register: dns_info

    - name: Show current DNS
      debug:
        var: dns_info

    - name: Set new DNS servers
      fortios_system_dns:
        vdom: "{{ vdom }}"
        system_dns:
          primary: "{{ primary_dns }}"
          secondary: "{{ secondary_dns }}"
          dns_over_tls: disable
