---
- name: Configuration de l'interface port1 sur FortiGate
  hosts: Fortigate
  connection: httpapi
  gather_facts: no

  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443

  tasks:
    - name: Configurer l'interface port1
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        state: "present"
        system_interface:
          name: "port1"
          vdom: "root"
          mode: "dhcp"
          allowaccess:
            - ping
            - https
            - ssh
            - http
            - fgfm
          type: "physical"
          alias: "LAN"
          snmp_index: 1
