---
- name: "Show FortiGate firewall policies where hint = 0 and last used = N/A"
  hosts: Fortigate
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortios

  vars:
    vdom_name: "root"

  tasks:
    - name: Get runtime stats for firewall policies
      fortios_monitor_fact:
        vdom: "{{ vdom_name }}"
        selector: "firewall_policy"
      register: monitor_policies

    - name: Show policies where hint = 0 and last used = N/A
      debug:
        msg: "⚠️ Policy ID {{ policy.policyid }} - '{{ policy.name | default('No Name') }}' has hint = 0 and Last used = N/A"
      loop: "{{ monitor_policies.meta.results }}"
      loop_control:
        loop_var: policy
      when:
        - policy.hitcount | default(0) == 0
        - policy.lastused | default('N/A') == 'N/A'
