---
- name: Configure IPsec VPN on FortiGate
  hosts: Fortigate
  connection: httpapi
  gather_facts: false
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"

  tasks:
    - name: Configure IPsec phase1-interface
      fortinet.fortios.fortios_vpn_ipsec_phase1_interface:
        vdom: "{{ vdom }}"
        state: "present"
        vpn_ipsec_phase1_interface:
          name: "to site1"
          interface: "port1"
          peertype: "any"
          net_device: "disable"
          proposal: "des-md5"
          comments: "VPN: to site1 (Created by VPN wizard)"
          remote_gw: "192.168.230.142"
          psksecret: "test12345"

    - name: Configure IPsec phase2-interface
      fortinet.fortios.fortios_vpn_ipsec_phase2_interface:
        vdom: "{{ vdom }}"
        state: "present"
        vpn_ipsec_phase2_interface:
          name: "to site1"
          phase1name: "to site1"
          proposal: "des-md5"
          comments: "VPN: to site1 (Created by VPN wizard)"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "to site1_local"
          dst_name: "to site1_remote"

    - name: Create firewall policy 1 - site1_local to site1_remote
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_policy:
          policyid: 1
          name: "vpn_to site1_local_0"
          uuid: "ed7d4844-4864-51f0-2165-019e89ea7699"
          srcintf:
            - name: "port2"
          dstintf:
            - name: "to site1"
          action: "accept"
          srcaddr:
            - name: "to site1_local"
          dstaddr:
            - name: "to site1_remote"
          schedule: "always"
          service:
            - name: "ALL"
          comments: "VPN: to site1 (Created by VPN wizard)"
          logtraffic: "all"

    - name: Create firewall policy 2 - site1_remote to site1_local
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_policy:
          policyid: 2
          name: "vpn_to site1_remote_0"
          uuid: "ed887a5c-4864-51f0-ebb0-874bbdd5af89"
          srcintf:
            - name: "to site1"
          dstintf:
            - name: "port2"
          action: "accept"
          srcaddr:
            - name: "to site1_remote"
          dstaddr:
            - name: "to site1_local"
          schedule: "always"
          service:
            - name: "ALL"
          comments: "VPN: to site1 (Created by VPN wizard)"
          logtraffic: "all"

    - name: Configure static route to site1
      fortinet.fortios.fortios_router_static:
        vdom: "{{ vdom }}"
        state: "present"
        router_static:
          seq_num: 3
          device: "to site1"
          comment: "VPN: to site1 (Created by VPN wizard)"
          dst: "10.10.20.1/24"
