---
- name: Configure IPsec VPN and Firewall Policies on FortiGate
  hosts: Fortigate
  connection: httpapi
  gather_facts: no

  vars:
    vdom: "root"

  tasks:
    - name: Configure IPsec Phase1 Interface
      fortinet.fortios.fortios_vpn_ipsec_phase1_interface:
        vdom: "{{ vdom }}"
        state: present
        vpn_ipsec_phase1_interface:
          name: "to site2"
          interface: "port1"
          peertype: "any"
          net_device: "disable"
          proposal: "des-md5"
          comments: "VPN: to site2 (Created by VPN wizard)"
          remote_gw: "192.168.230.128"
          psksecret: "test12345"
    - name: Configure IPsec Phase2 Interface
      fortinet.fortios.fortios_vpn_ipsec_phase2_interface:
        vdom: "{{ vdom }}"
        state: present
        vpn_ipsec_phase2_interface:
          name: "to site2"
          phase1name: "to site2"
          proposal: "des-md5"
          comments: "VPN: to site2 (Created by VPN wizard)"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "to_site2_local"
          dst_name: "to_site2_remote"

    - name: Create firewall policy to site2
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        firewall_policy:
          policyid: 1
          name: "to site2"
          uuid: "56eaf1a0-4a22-51f0-4641-66f66cf613d3"
          srcintf:
            - name: "port2"
          dstintf:
            - name: "to site2"
          action: "accept"
          srcaddr:
            - name: "to_site2_local"
          dstaddr:
            - name: "to_site2_remote"
          schedule: "always"
          service:
            - name: "ALL"
          comments: "VPN: to site2 (Created by VPN wizard)"

    - name: Create firewall policy from site2 to local
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        firewall_policy:
          policyid: 2
          name: "vpn_to site2_remote_0"
          uuid: "5702bcea-4a22-51f0-57a2-497889b925e7"
          srcintf:
            - name: "to site2"
          dstintf:
            - name: "port2"
          action: "accept"
          srcaddr:
            - name: "to_site2_remote"
          dstaddr:
            - name: "to_site2_local"
          schedule: "always"
          service:
            - name: "ALL"
          comments: "VPN: to site2 (Created by VPN wizard)"

    - name: Configure static route for VPN to site2
      fortinet.fortios.fortios_router_static:
        vdom: "{{ vdom }}"
        state: present
        router_static:
          seq_num: 1
          device: "to site2"
          dst: "10.10.10.0/24"
